<?php

/**
 * @file
 * Primary module hooks for Daily Verse module.
 */
/**
 * Implements hook_theme().
 */
function daily_verse_theme() {
    return [
      'verse_display' => [
        'variables' => [
          'verse_text' => NULL,
          'verse_reference' => NULL,
        ],
        'template' => 'verse-display', // Refers to verse-display.html.twig
      ],
    ];
  }


  function daily_verse_preprocess_page(&$variables) {
    // Check if the current route matches your custom page
    $route_name = \Drupal::routeMatch()->getRouteName();
    if ($route_name == 'daily_verse.verse_display') {
      // Unset regions for navbar, footer, and page title
      unset($variables['page']['navbar']);
      unset($variables['page']['footer']);
      unset($variables['page']['title']);
    }
  }
  
  